def errorInOuter():
    print(y)
    def inner():
        return y
    y = 1

def errorInInner():
    def inner():
        return y
    inner()
    y = 1

#___assertRaises(UnboundLocalError, errorInOuter)
___assertRaises(NameError, errorInInner)

#def test():
#    method_and_var = "var"
#    class Test:
#        def method_and_var(self):
#            return "method"
#        def test(self):
#            return method_and_var
#    return Test()

#t=test()
#print(t.test())




#a = {1:1, 2:2}

#for b in iter(a), a.keys(), a.items():
#    print(b)
